In [ ]:
#!pip install openpyxl

In [2]:
import seaborn as sns
from statistics import *
from statistics import stdev
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import openpyxl

In [ ]:
'''file = r'../input/bysykk/Bysykkeloversikt_2019.xlsx'
xl = pd.ExcelFile(file)
print(xl.sheet_names)
df1 = xl.parse('Analyse')'''

In [ ]:
'''df1 = xl.parse('juli_2019')
df1'''

In [ ]:
'''
file = r'../input/public/Public_transportation_infrastructure.xlsx'
xl2 = pd.ExcelFile(file)
print(xl2.sheet_names)
#df1 = xl.parse('Analyse')
df9 = pd.read_excel(xl2, 'Sheet6')
df9.to_pickle('Sheet6.pkl')
'''

In [ ]:
#['Analyse', 'april_2019', 'mai_2019', 'juni_2019', 'juli_2019', 'august_2019', 'september_2019', 'oktober_2019']

In [ ]:
'''df1 = pd.read_excel(xl, 'Analyse')
df1.to_pickle('Analyse.pkl')

df2 = pd.read_excel(xl, 'april_2019')
df2.to_pickle('april_2019.pkl')

df3 = pd.read_excel(xl, 'mai_2019')
df3.to_pickle('mai_2019.pkl')

df4 = pd.read_excel(xl, 'juni_2019')
df4.to_pickle('juni_2019.pkl')

df5 = pd.read_excel(xl, 'juli_2019')
df5.to_pickle('juli_2019.pkl')

df6 = pd.read_excel(xl, 'august_2019')
df6.to_pickle('august_2019.pkl')

df7 = pd.read_excel(xl, 'september_2019')
df7.to_pickle('september_2019.pkl')

df8 = pd.read_excel(xl, 'oktober_2019')
df8.to_pickle('oktober_2019.pkl')
'''

In [3]:
df1 = pd.read_pickle(r'../input/dataset-pkl/Analyse.pkl')
df3 = pd.read_pickle(r'../input/dataset-pkl/april_2019.pkl')
df4 = pd.read_pickle(r'../input/dataset-pkl/mai_2019.pkl')
df5 = pd.read_pickle(r'../input/dataset-pkl/juni_2019.pkl')
df6 = pd.read_pickle(r'../input/dataset-pkl/juli_2019.pkl')
df7 = pd.read_pickle(r'../input/dataset-pkl/august_2019.pkl')
df8 = pd.read_pickle(r'../input/dataset-pkl/september_2019.pkl')
df9 = pd.read_pickle(r'../input/dataset-pkl/oktober_2019.pkl')
#df11 = pd.read_pickle(r'../input/dataset-pkl/Sheet6.pkl')

In [4]:
df1=df1.dropna(axis=1,how='all')
df1

,2019-04-01 00:00:00,Unnamed: 1,2019-05-01 00:00:00,Unnamed: 4,2019-06-01 00:00:00,Unnamed: 7,2019-07-01 00:00:00,Unnamed: 10,2019-08-01 00:00:00,Unnamed: 13,2019-09-01 00:00:00,Unnamed: 16,2019-10-01 00:00:00,Unnamed: 19
0,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at
1,7 Juni Plassen,1293,7 Juni Plassen,1879,7 Juni Plassen,1943,7 Juni Plassen,1565,7 Juni Plassen,2622,7 Juni Plassen,2546,7 Juni Plassen,1718
2,Adamstuen,567,Adamstuen,904,Adamstuen,825,Adamstuen,671,Adamstuen,899,Adamstuen,745,Adamstuen,473
3,AHO,1799,AHO,2331,AHO,2244,AHO,1865,AHO,2691,AHO,2362,AHO,1662
4,Akersgata,2418,Akersgata,3116,Akersgata,3021,Akersgata,2617,Akersgata,3464,Akersgata,2747,Akersgata,2056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,NaN,NaN,NaN,NaN,NaN,NaN,Økernveien,302,Vulkan,2709,Totalsum,292586,Økernveien,185
250,NaN,NaN,NaN,NaN,NaN,NaN,Totalsum,310955,Vålerenga,1087,NaN,NaN,Totalsum,193868
251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vår Frelsers gravlund sør,3375,NaN,NaN,NaN,NaN
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Økernveien,527,NaN,NaN,NaN,NaN
253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Totalsum,389270,NaN,NaN,NaN,NaN

In [5]:
for col in df1.columns:
    print(col)

2019-04-01 00:00:00
Unnamed: 1
2019-05-01 00:00:00
Unnamed: 4
2019-06-01 00:00:00
Unnamed: 7
2019-07-01 00:00:00
Unnamed: 10
2019-08-01 00:00:00
Unnamed: 13
2019-09-01 00:00:00
Unnamed: 16
2019-10-01 00:00:00
Unnamed: 19

In [6]:
df1=df1.rename(columns={'Unnamed: 1':'c_april'})
df1=df1.rename(columns={'Unnamed: 4':'c_may'})
df1=df1.rename(columns={'Unnamed: 7':'c_jun'})
df1=df1.rename(columns={'Unnamed: 10':'c_july'})
df1=df1.rename(columns={'Unnamed: 13':'c_aug'})
df1=df1.rename(columns={'Unnamed: 16':'c_sep'})
df1=df1.rename(columns={'Unnamed: 19':'c_oct'})

df1

,2019-04-01 00:00:00,c_april,2019-05-01 00:00:00,c_may,2019-06-01 00:00:00,c_jun,2019-07-01 00:00:00,c_july,2019-08-01 00:00:00,c_aug,2019-09-01 00:00:00,c_sep,2019-10-01 00:00:00,c_oct
0,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at
1,7 Juni Plassen,1293,7 Juni Plassen,1879,7 Juni Plassen,1943,7 Juni Plassen,1565,7 Juni Plassen,2622,7 Juni Plassen,2546,7 Juni Plassen,1718
2,Adamstuen,567,Adamstuen,904,Adamstuen,825,Adamstuen,671,Adamstuen,899,Adamstuen,745,Adamstuen,473
3,AHO,1799,AHO,2331,AHO,2244,AHO,1865,AHO,2691,AHO,2362,AHO,1662
4,Akersgata,2418,Akersgata,3116,Akersgata,3021,Akersgata,2617,Akersgata,3464,Akersgata,2747,Akersgata,2056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,NaN,NaN,NaN,NaN,NaN,NaN,Økernveien,302,Vulkan,2709,Totalsum,292586,Økernveien,185
250,NaN,NaN,NaN,NaN,NaN,NaN,Totalsum,310955,Vålerenga,1087,NaN,NaN,Totalsum,193868
251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vår Frelsers gravlund sør,3375,NaN,NaN,NaN,NaN
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Økernveien,527,NaN,NaN,NaN,NaN
253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Totalsum,389270,NaN,NaN,NaN,NaN

In [7]:
df1.columns.tolist()

[datetime.datetime(2019, 4, 1, 0, 0),
 'c_april',
 datetime.datetime(2019, 5, 1, 0, 0),
 'c_may',
 datetime.datetime(2019, 6, 1, 0, 0),
 'c_jun',
 datetime.datetime(2019, 7, 1, 0, 0),
 'c_july',
 datetime.datetime(2019, 8, 1, 0, 0),
 'c_aug',
 datetime.datetime(2019, 9, 1, 0, 0),
 'c_sep',
 datetime.datetime(2019, 10, 1, 0, 0),
 'c_oct']

In [8]:
import datetime
import os
import csv
from datetime import datetime
df1 = df1.rename(columns={datetime.strptime('2019-04-01 00:00:00', '%Y-%m-%d %H:%M:%S'): '04'})
df1 = df1.rename(columns={datetime.strptime('2019-05-01 00:00:00', '%Y-%m-%d %H:%M:%S'): '05'})
df1 = df1.rename(columns={datetime.strptime('2019-06-01 00:00:00', '%Y-%m-%d %H:%M:%S'): '06'})
df1 = df1.rename(columns={datetime.strptime('2019-07-01 00:00:00', '%Y-%m-%d %H:%M:%S'): '07'})
df1 = df1.rename(columns={datetime.strptime('2019-08-01 00:00:00', '%Y-%m-%d %H:%M:%S'): '08'})
df1 = df1.rename(columns={datetime.strptime('2019-09-01 00:00:00', '%Y-%m-%d %H:%M:%S'): '09'})
df1 = df1.rename(columns={datetime.strptime('2019-10-01 00:00:00', '%Y-%m-%d %H:%M:%S'): '10'})

In [9]:
df1

,04,c_april,05,c_may,06,c_jun,07,c_july,08,c_aug,09,c_sep,10,c_oct
0,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at,Radetiketter,Antall av ended_at
1,7 Juni Plassen,1293,7 Juni Plassen,1879,7 Juni Plassen,1943,7 Juni Plassen,1565,7 Juni Plassen,2622,7 Juni Plassen,2546,7 Juni Plassen,1718
2,Adamstuen,567,Adamstuen,904,Adamstuen,825,Adamstuen,671,Adamstuen,899,Adamstuen,745,Adamstuen,473
3,AHO,1799,AHO,2331,AHO,2244,AHO,1865,AHO,2691,AHO,2362,AHO,1662
4,Akersgata,2418,Akersgata,3116,Akersgata,3021,Akersgata,2617,Akersgata,3464,Akersgata,2747,Akersgata,2056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,NaN,NaN,NaN,NaN,NaN,NaN,Økernveien,302,Vulkan,2709,Totalsum,292586,Økernveien,185
250,NaN,NaN,NaN,NaN,NaN,NaN,Totalsum,310955,Vålerenga,1087,NaN,NaN,Totalsum,193868
251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vår Frelsers gravlund sør,3375,NaN,NaN,NaN,NaN
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Økernveien,527,NaN,NaN,NaN,NaN
253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Totalsum,389270,NaN,NaN,NaN,NaN

In [10]:
df1.to_dict()

{'04': {0: 'Radetiketter',
  1: '7 Juni Plassen',
  2: 'Adamstuen',
  3: 'AHO',
  4: 'Akersgata',
  5: 'Alexander Kiellands Plass',
  6: 'Anker Hostel',
  7: 'Annette Thommessens Plass',
  8: 'Arendalsgata',
  9: 'Arkaden Nord',
  10: 'Arkaden Sør',
  11: 'Arkitekt Rivertz Plass',
  12: 'Badebakken',
  13: 'Bak Niels Treschows hus nord',
  14: 'Bak Niels Treschows hus sør',
  15: 'Bankplassen',
  16: 'Bentsebrugata',
  17: 'Bernt Ankers gate',
  18: 'BI Nydalen',
  19: 'Birkelunden',
  20: "Biskop Gunnerus' gate",
  21: 'Bislett Stadion',
  22: 'Bislettgata',
  23: 'Bjerregaards gate',
  24: 'Bjerregaardsgate Øst',
  25: 'Bjølsen mølle',
  26: 'Bjølsen Studentby',
  27: 'Bjølsendumpa',
  28: 'Bjørvika',
  29: 'Blindern studentparkering',
  30: 'Bogstadveien',
  31: 'Botanisk Hage sør',
  32: 'Botanisk hage sør-vest',
  33: 'Botanisk Hage vest',
  34: 'Briskeby',
  35: 'Bryn T-Bane',
  36: 'Bygdøy allé',
  37: 'Bøkkerveien',
  38: 'Carl Berners plass sør',
  39: 'Chr. Michelsens Gate',
  40: 'Colbjørnsens gate',
  41: 'Colletts gate',
  42: 'Colosseum Kino',
  43: 'Det Teologiske fakultet',
  44: 'Diakonhjemmet',
  45: 'Dokkveien',
  46: 'Drammensveien',
  47: 'Dyvekes bru',
  48: 'Dælenenggata',
  49: 'Edvard Storms gate',
  50: 'Ensjø T-Bane',
  51: 'Ensjøveien',
  52: 'Fagerheimgata',
  53: 'Filipstadveien',
  54: 'Finnmarksgata',
  55: 'Forskningsveien',
  56: 'Fram-gården',
  57: 'Fred Olsens gate',
  58: 'Fredensborg',
  59: 'Friggfeltet',
  60: 'Frogner plass',
  61: 'Frogner Stadion',
  62: 'Frogner Tennisklubb',
  63: 'Frognerbadet',
  64: 'Frognerstranda',
  65: 'Frognerveien',
  66: 'Frøen T-bane',
  67: 'Furulund',
  68: 'Fyrstikktorget',
  69: 'Fysikkbygningen',
  70: 'Galgeberg',
  71: 'Gaustad T-bane',
  72: 'Georg Morgenstiernes hus',
  73: 'Gimle Kino',
  74: 'Goethe Institut',
  75: 'Grenseveien',
  76: 'Griffenfeldts gate',
  77: 'Grünerhagen Nord',
  78: 'Grønlands torg',
  79: 'Hallénparken',
  80: 'Hallings gate',
  81: 'Hammersborg Torg',
  82: 'Hans Nielsen Hauges plass',
  83: 'Hasle',
  84: 'Hasle Torg',
  85: 'HasleLinje',
  86: 'Hausmanns bru',
  87: 'Hausmanns gate',
  88: 'Helga Helgesens plass',
  89: 'Henrik Ibsens gate',
  90: 'HiOA',
  91: 'Hoff terrasse holdeplass',
  92: 'Hoffsveien',
  93: 'Holbergs Plass',
  94: 'Huitfeldts gate',
  95: 'Huk',
  96: 'Hydroparken',
  97: 'Idioten',
  98: 'Ila',
  99: 'Jakob kirke',
  100: 'Jarlsborgveien',
  101: 'Jenny Braatens Plass',
  102: 'Jens Bjelkes gate',
  103: 'Jernbanetorget',
  104: 'Jess Carlsens gate',
  105: 'John Colletts plass',
  106: 'Jordalgata',
  107: 'Kampen park Øst',
  108: 'Karenlyst allé',
  109: 'Kirkegata 15',
  110: 'Kirkeristen',
  111: 'Kirkeveien',
  112: 'Kjeld Stubs gate',
  113: 'Kontraskjæret',
  114: "Krebs' gate",
  115: 'Kværnerbyen',
  116: 'Københavngata busstopp',
  117: 'Lakkegata',
  118: 'Landstads gate',
  119: 'Langkaia',
  120: 'Lille Grensen',
  121: 'Lilleborgbanen',
  122: 'Linaaes gate',
  123: 'Lindern',
  124: 'Lodalen busstopp',
  125: 'Lørenveien',
  126: 'Mailundveien',
  127: 'Majorstua skole',
  128: 'Majorstuen',
  129: 'Majorstuen t-bane',
  130: 'Majorstuveien',
  131: 'Mandalls gate',
  132: 'Marienlyst',
  133: 'Marienlystparken',
  134: 'Meltzers gate',
  135: 'Monolittveien',
  136: 'Munkedamsveien',
  137: 'Munkegata trikkestopp',
  138: 'Myraløkka Øst',
  139: 'Mølleparken',
  140: 'Møllergata',
  141: 'Nedre Slottsgate',
  142: 'Nordre gate',
  143: 'Norsk Folkemuseum',
  144: 'Nydalen',
  145: 'Nylandsveien',
  146: 'Olaf Ryes plass',
  147: 'Olav Vs gate',
  148: 'Oscars gate',
  149: 'Oslo Handelsgymnasium',
  150: 'Oslo Hospital',
  151: 'Oslo Plaza',
  152: 'Over Rådhusgata',
  153: 'Paléhaven',
  154: 'Parkveien',
  155: 'Pilestredet',
  156: 'Pilestredet 63',
  157: 'Pilestredet Studenthus',
  158: 'Riddervoldplass',
  159: 'Ringnes Park',
  160: 'Rolf Wickstrøms vei',
  161: 'Ruseløkkgården',
  162: 'Rådhusbrygge 4',
  163: 'Rådhusgata',
  164: 'Saga Kino',
  165: 'Sagene bussholdeplass',
  166: 'Salt',
  167: 'Schives gate',
  168: 'Schous plass',
  169: 'Schous plass trikkestopp',
  170: 'Sentrum Scene',
  171: 'Sinsen T-bane',
  172: 'Sinsenveien',
  173: 'Sirkustomta',
  174: 'Sjølyst',
  175: 'Sjøsiden vest',
  176: 'Sjøsiden øst',
  177: 'Skarpsnoparken',
  178: 'Skillebekk',
  179: 'Skippergata',
  180: 'Skovveien',
  181: 'Skråninga',
  182: 'Skøyen',
  183: 'Skøyen Stasjon',
  184: 'Slemdalsveien',
  185: 'Slottsparken Øst',
  186: 'Sofienberggata',
  187: 'Sofienbergparken nord',
  188: 'Sofienbergparken nordvest',
  189: 'Sofienbergparken sør',
  190: 'Sognsveien',
  191: 'Sommerfrydhagen',
  192: 'Sotahjørnet',
  193: 'Spikersuppa Vest',
  194: 'Spikersuppa Øst',
  195: 'St. Hanshaugen',
  196: 'St. Hanshaugen park nord',
  197: 'St. Hanshaugen park sør',
  198: 'St. Hanshaugen park vest',
  199: 'St. Olavs gate',
  200: 'Stavangergata',
  201: 'Stensgata',
  202: 'Stensparken',
  203: 'Stockfleths gate',
  204: 'Storgata',
  205: 'Storo Storsenter',
  206: 'Studenterlunden',
  207: 'Studentparlamentet',
  208: 'Suhms gate',
  209: 'Sukkerbiten',
  210: 'Søndre gate',
  211: 'Sørvest for Slottsparken',
  212: 'Tannlegehøyskolen',
  213: 'Thereses gate',
  214: 'Thomas Heftyes plass',
  215: 'Thune',
  216: 'Tjuvholmen',
  217: 'Tordenskiolds gate',
  218: 'Torggata',
  219: 'Torshovdalen øst',
  220: 'Torshovparken vest',
  221: 'Trelastgata',
  222: 'Trondheimsveien',
  223: 'Tøyen skole',
  224: 'Tøyenbekken',
  225: 'Tøyenparken',
  226: 'Tåsen Senter',
  227: 'Tåsenløkka',
  228: 'Uelands gate',
  229: 'Ullevål sykehus',
  230: 'Ullevålsalléen',
  231: 'Ullevålsveien',
  232: 'Uranienborgparken',
  233: 'Uranienborgveien',
  234: 'Valkyrieplassen',
  235: 'Vaterlandsparken',
  236: 'Vaterlandsparken II',
  237: 'Vestkanttorvet',
  238: 'Vippetangen vest',
  239: 'Vippetangen øst',
  240: 'Volvat',
  241: 'Vulkan',
  242: 'Vålerenga',
  243: 'Vår Frelsers gravlund sør',
  244: 'Økernveien',
  245: 'Totalsum',
  246: nan,
  247: nan,
  248: nan,
  249: nan,
  250: nan,
  251: nan,
  252: nan,
  253: nan},
 'c_april': {0: 'Antall av ended_at',
  1: 1293,
  2: 567,
  3: 1799,
  4: 2418,
  5: 3238,
  6: 1395,
  7: 998,
  8: 543,
  9: 1315,
  10: 1103,
  11: 352,
  12: 226,
  13: 318,
  14: 175,
  15: 1846,
  16: 606,
  17: 1511,
  18: 524,
  19: 2258,
  20: 1097,
  21: 2299,
  22: 696,
  23: 1545,
  24: 621,
  25: 186,
  26: 565,
  27: 275,
  28: 2058,
  29: 144,
  30: 1619,
  31: 1968,
  32: 739,
  33: 925,
  34: 545,
  35: 137,
  36: 516,
  37: 93,
  38: 1162,
  39: 845,
  40: 455,
  41: 189,
  42: 622,
  43: 281,
  44: 214,
  45: 1455,
  46: 426,
  47: 809,
  48: 612,
  49: 1136,
  50: 168,
  51: 226,
  52: 1262,
  53: 2083,
  54: 501,
  55: 161,
  56: 1031,
  57: 1732,
  58: 1569,
  59: 264,
  60: 1376,
  61: 691,
  62: 238,
  63: 454,
  64: 1398,
  65: 585,
  66: 111,
  67: 113,
  68: 186,
  69: 336,
  70: 615,
  71: 70,
  72: 297,
  73: 999,
  74: 129,
  75: 106,
  76: 570,
  77: 1065,
  78: 1857,
  79: 1092,
  80: 770,
  81: 1377,
  82: 460,
  83: 73,
  84: 309,
  85: 67,
  86: 752,
  87: 886,
  88: 2960,
  89: 900,
  90: 1151,
  91: 470,
  92: 351,
  93: 1202,
  94: 1265,
  95: 1191,
  96: 811,
  97: 228,
  98: 183,
  99: 2292,
  100: 91,
  101: 593,
  102: 1647,
  103: 3045,
  104: 1487,
  105: 154,
  106: 540,
  107: 61,
  108: 1473,
  109: 666,
  110: 1940,
  111: 222,
  112: 413,
  113: 1107,
  114: 455,
  115: 1144,
  116: 302,
  117: 1403,
  118: 508,
  119: 597,
  120: 1450,
  121: 572,
  122: 1173,
  123: 159,
  124: 272,
  125: 328,
  126: 126,
  127: 519,
  128: 1739,
  129: 146,
  130: 629,
  131: 993,
  132: 340,
  133: 481,
  134: 258,
  135: 114,
  136: 611,
  137: 1601,
  138: 687,
  139: 835,
  140: 1317,
  141: 710,
  142: 1462,
  143: 909,
  144: 115,
  145: 1375,
  146: 3333,
  147: 1546,
  148: 1149,
  149: 1008,
  150: 970,
  151: 923,
  152: 958,
  153: 2690,
  154: 1204,
  155: 504,
  156: 750,
  157: 709,
  158: 503,
  159: 3039,
  160: 25,
  161: 925,
  162: 6101,
  163: 832,
  164: 1926,
  165: 631,
  166: 871,
  167: 492,
  168: 2633,
  169: 1576,
  170: 2639,
  171: 140,
  172: 211,
  173: 691,
  174: 408,
  175: 1902,
  176: 3281,
  177: 197,
  178: 1197,
  179: 884,
  180: 780,
  181: 1743,
  182: 1019,
  183: 387,
  184: 704,
  185: 754,
  186: 951,
  187: 1897,
  188: 1578,
  189: 995,
  190: 311,
  191: 1290,
  192: 288,
  193: 2413,
  194: 1971,
  195: 939,
  196: 311,
  197: 502,
  198: 548,
  199: 2079,
  200: 408,
  201: 669,
  202: 799,
  203: 168,
  204: 1272,
  205: 524,
  206: 1764,
  207: 767,
  208: 522,
  209: 3534,
  210: 1937,
  211: 324,
  212: 350,
  213: 330,
  214: 1213,
  215: 596,
  216: 3301,
  217: 599,
  218: 4493,
  219: 260,
  220: 291,
  221: 908,
  222: 391,
  223: 2197,
  224: 1490,
  225: 525,
  226: 102,
  227: 236,
  228: 474,
  229: 657,
  230: 162,
  231: 271,
  232: 428,
  233: 1131,
  234: 946,
  235: 2633,
  236: 985,
  237: 558,
  238: 1555,
  239: 734,
  240: 186,
  241: 1632,
  242: 333,
  243: 2067,
  244: 212,
  245: 235713,
  246: nan,
  247: nan,
  248: nan,
  249: nan,
  250: nan,
  251: nan,
  252: nan,
  253: nan},
 '05': {0: 'Radetiketter',
  1: '7 Juni Plassen',
  2: 'Adamstuen',
  3: 'AHO',
  4: 'Akersgata',
  5: 'Alexander Kiellands Plass',
  6: 'Anker Hostel',
  7: 'Annette Thommessens Plass',
  8: 'Arendalsgata',
  9: 'Arkaden Nord',
  10: 'Arkaden Sør',
  11: 'Arkitekt Rivertz Plass',
  12: 'Badebakken',
  13: 'Bak Niels Treschows hus nord',
  14: 'Bak Niels Treschows hus sør',
  15: 'Bankplassen',
  16: 'Bentsebrugata',
  17: 'Bernt Ankers gate',
  18: 'BI Nydalen',
  19: 'Birkelunden',
  20: "Biskop Gunnerus' gate",
  21: 'Bislett Stadion',
  22: 'Bislettgata',
  23: 'Bjerregaards gate',
  24: 'Bjerregaardsgate Øst',
  25: 'Bjølsen mølle',
  26: 'Bjølsen Studentby',
  27: 'Bjølsendumpa',
  28: 'Bjørvika',
  29: 'Blindern studentparkering',
  30: 'Bogstadveien',
  31: 'Botanisk Hage sør',
  32: 'Botanisk hage sør-vest',
  33: 'Botanisk Hage vest',
  34: 'Briskeby',
  35: 'Bryn T-Bane',
  36: 'Bygdøy allé',
  37: 'Bøkkerveien',
  38: 'Carl Berners plass sør',
  39: 'Chr. Michelsens Gate',
  40: 'Colbjørnsens gate',
  41: 'Colosseum Kino',
  42: 'Det Teologiske fakultet',
  43: 'Diakonhjemmet',
  44: 'Dokkveien',
  45: 'Dyvekes bru',
  46: 'Dælenenggata',
  47: 'Edvard Storms gate',
  48: 'Elisenberg',
  49: 'Ensjø T-Bane',
  50: 'Ensjøveien',
  51: 'Fagerheimgata',
  52: 'Filipstadveien',
  53: 'Finnmarksgata',
  54: 'Forskningsveien',
  55: 'Fram-gården',
  56: 'Fred Olsens gate',
  57: 'Fredensborg',
  58: 'Friggfeltet',
  59: 'Frogner plass',
  60: 'Frogner Stadion',
  61: 'Frogner Tennisklubb',
  62: 'Frognerbadet',
  63: 'Frognerstranda',
  64: 'Frognerveien',
  65: 'Frøen T-bane',
  66: 'Furulund',
  67: 'Fyrstikktorget',
  68: 'Fysikkbygningen',
  69: 'Galgeberg',
  70: 'Gaustad T-bane',
  71: 'Georg Morgenstiernes hus',
  72: 'Gimle Kino',
  73: 'Grenseveien',
  74: 'Griffenfeldts gate',
  75: 'Grünerhagen Nord',
  76: 'Grønlands torg',
  77: 'Hallénparken',
  78: 'Hallings gate',
  79: 'Hammersborg Torg',
  80: 'Hans Nielsen Hauges plass',
  81: 'Hasle',
  82: 'Hasle Torg',
  83: 'HasleLinje',
  84: 'Hausmanns bru',
  85: 'Hausmanns gate',
  86: 'Helga Helgesens plass',
  87: 'Henrik Ibsens gate',
  88: 'Henrik Wergelands allé',
  89: 'HiOA',
  90: 'Hoff terrasse holdeplass',
  91: 'Hoffsveien',
  92: 'Holbergs Plass',
  93: 'Huitfeldts gate',
  94: 'Huk',
  95: 'Hydroparken',
  96: 'Idioten',
  97: 'Ila',
  98: 'Jakob kirke',
  99: 'Jarlsborgveien',
  100: 'Jenny Braatens Plass',
  101: 'Jens Bjelkes gate',
  102: 'Jernbanetorget',
  103: 'Jess Carlsens gate',
  104: 'John Colletts plass',
  105: 'Jordalgata',
  106: 'Kampen park Øst',
  107: 'Karenlyst allé',
  108: 'Kirkegata 15',
  109: 'Kirkeristen',
  110: 'Kirkeveien',
  111: 'Kjeld Stubs gate',
  112: 'Kontraskjæret',
  113: "Krebs' gate",
  114: 'Kværnerbyen',
  115: 'Københavngata busstopp',
  116: 'Lakkegata',
  117: 'Landstads gate',
  118: 'Langkaia',
  119: 'Lille Grensen',
  120: 'Lilleborgbanen',
  121: 'Linaaes gate',
  122: 'Lindern',
  123: 'Lodalen busstopp',
  124: 'Lørenveien',
  125: 'Mailundveien',
  126: 'Majorstua skole',
  127: 'Majorstuen',
  128: 'Majorstuen t-bane',
  129: 'Majorstuveien',
  130: 'Mandalls gate',
  131: 'Marienlyst',
  132: 'Marienlystparken',
  133: 'Meltzers gate',
  134: 'Monolittveien',
  135: 'Munkedamsveien',
  136: 'Munkegata trikkestopp',
  137: 'Myraløkka Øst',
  138: 'Mølleparken',
  139: 'Møllergata',
  140: 'Nedre Slottsgate',
  141: 'Nordre gate',
  142: 'Norsk Folkemuseum',
  143: 'Nydalen',
  144: 'Nylandsveien',
  145: 'Olaf Ryes plass',
  146: 'Olav Vs gate',
  147: 'Oscars gate',
  148: 'Oslo Handelsgymnasium',
  149: 'Oslo Hospital',
  150: 'Oslo Plaza',
  151: 'Over Rådhusgata',
  152: 'Paléhaven',
  153: 'Parkveien',
  154: 'Pilestredet',
  155: 'Pilestredet 63',
  156: 'Pilestredet Studenthus',
  157: 'Riddervoldplass',
  158: 'Ringnes Park',
  159: 'Rolf Wickstrøms vei',
  160: 'Ruseløkkgården',
  161: 'Rådhusbrygge 4',
  162: 'Rådhusgata',
  163: 'Saga Kino',
  164: 'Sagene bussholdeplass',
  165: 'Salt',
  166: 'Schives gate',
  167: 'Schous plass',
  168: 'Schous plass trikkestopp',
  169: 'Sentrum Scene',
  170: 'Sinsen T-bane',
  171: 'Sinsenveien',
  172: 'Sirkustomta',
  173: 'Sjølyst',
  174: 'Sjøsiden vest',
  175: 'Sjøsiden øst',
  176: 'Skarpsnoparken',
  177: 'Skillebekk',
  178: 'Skippergata',
  179: 'Skovveien',
  180: 'Skråninga',
  181: 'Skøyen',
  182: 'Skøyen Stasjon',
  183: 'Slemdalsveien',
  184: 'Slottsparken Øst',
  185: 'Sofienberggata',
  186: 'Sofienbergparken nord',
  187: 'Sofienbergparken nordvest',
  188: 'Sofienbergparken sør',
  189: 'Sognsveien',
  190: 'Sommerfrydhagen',
  191: 'Sotahjørnet',
  192: 'Spikersuppa Vest',
  193: 'Spikersuppa Øst',
  194: 'St. Hanshaugen',
  195: 'St. Hanshaugen park nord',
  196: 'St. Hanshaugen park sør',
  197: 'St. Hanshaugen park vest',
  198: 'St. Olavs gate',
  199: 'Stavangergata',
  200: 'Stensgata',
  201: 'Stensparken',
  202: 'Stockfleths gate',
  203: 'Storgata',
  204: 'Storo Storsenter',
  205: 'Studenterlunden',
  206: 'Studentparlamentet',
  207: 'Suhms gate',
  208: 'Sukkerbiten',
  209: 'Søndre gate',
  210: 'Sørvest for Slottsparken',
  211: 'Tannlegehøyskolen',
  212: 'Thereses gate',
  213: 'Thomas Heftyes plass',
  214: 'Thune',
  215: 'Tjuvholmen',
  216: 'Tordenskiolds gate',
  217: 'Torggata',
  218: 'Torshovdalen øst',
  219: 'Torshovparken vest',
  220: 'Trelastgata',
  221: 'Trondheimsveien',
  222: 'Tøyen skole',
  223: 'Tøyenbekken',
  224: 'Tøyenparken',
  225: 'Tåsen Senter',
  226: 'Tåsenløkka',
  227: 'Uelands gate',
  228: 'Ullevål sykehus',
  229: 'Ullevålsalléen',
  230: 'Ullevålsveien',
  231: 'Uranienborgparken',
  232: 'Uranienborgveien',
  233: 'Valkyrieplassen',
  234: 'Vaterlandsparken',
  235: 'Vaterlandsparken II',
  236: 'Vestkanttorvet',
  237: 'Vippetangen vest',
  238: 'Vippetangen øst',
  239: 'Volvat',
  240: 'Vulkan',
  241: 'Vålerenga',
  242: 'Vår Frelsers gravlund sør',
  243: 'Økernveien',
  244: 'Totalsum',
  245: nan,
  246: nan,
  247: nan,
  248: nan,
  249: nan,
  250: nan,
  251: nan,
  252: nan,
  253: nan},
 'c_may': {0: 'Antall av ended_at',
  1: 1879,
  2: 904,
  3: 2331,
  4: 3116,
  5: 4306,
  6: 1579,
  7: 1212,
  8: 887,
  9: 1792,
  10: 1176,
  11: 602,
  12: 409,
  13: 391,
  14: 245,
  15: 3142,
  16: 955,
  17: 1881,
  18: 764,
  19: 2841,
  20: 1262,
  21: 3361,
  22: 782,
  23: 2177,
  24: 1136,
  25: 357,
  26: 818,
  27: 479,
  28: 3738,
  29: 258,
  30: 2924,
  31: 2398,
  32: 1046,
  33: 1244,
  34: 869,
  35: 143,
  36: 718,
  37: 167,
  38: 1646,
  39: 1196,
  40: 840,
  41: 986,
  42: 391,
  43: 304,
  44: 1711,
  45: 1206,
  46: 987,
  47: 1712,
  48: 343,
  49: 388,
  50: 272,
  51: 1812,
  52: 2242,
  53: 657,
  54: 241,
  55: 1489,
  56: 1788,
  57: 2100,
  58: 330,
  59: 1611,
  60: 929,
  61: 489,
  62: 620,
  63: 1544,
  64: 884,
  65: 214,
  66: 138,
  67: 286,
  68: 445,
  69: 1007,
  70: 156,
  71: 491,
  72: 1277,
  73: 168,
  74: 721,
  75: 1491,
  76: 1731,
  77: 1485,
  78: 1178,
  79: 1948,
  80: 612,
  81: 135,
  82: 465,
  83: 150,
  84: 1112,
  85: 1118,
  86: 4086,
  87: 1512,
  88: 214,
  89: 1663,
  90: 664,
  91: 453,
  92: 1643,
  93: 1984,
  94: 750,
  95: 1018,
  96: 598,
  97: 563,
  98: 3194,
  99: 132,
  100: 803,
  101: 2314,
  102: 3278,
  103: 2262,
  104: 407,
  105: 722,
  106: 174,
  107: 1925,
  108: 871,
  109: 1973,
  110: 435,
  111: 559,
  112: 1281,
  113: 711,
  114: 1691,
  115: 460,
  116: 2015,
  117: 976,
  118: 629,
  119: 1640,
  120: 909,
  121: 886,
  122: 197,
  123: 419,
  124: 387,
  125: 232,
  126: 648,
  127: 2087,
  128: 283,
  129: 950,
  130: 1259,
  131: 583,
  132: 673,
  133: 429,
  134: 258,
  135: 760,
  136: 2085,
  137: 1112,
  138: 1325,
  139: 1784,
  140: 1086,
  141: 1458,
  142: 765,
  143: 125,
  144: 1646,
  145: 4062,
  146: 1596,
  147: 550,
  148: 1426,
  149: 1248,
  150: 1195,
  151: 1055,
  152: 3364,
  153: 1991,
  154: 906,
  155: 1400,
  156: 1044,
  157: 809,
  158: 4298,
  159: 39,
  160: 1241,
  161: 6339,
  162: 1018,
  163: 2305,
  164: 929,
  165: 913,
  166: 872,
  167: 3516,
  168: 2029,
  169: 4718,
  170: 311,
  171: 311,
  172: 928,
  173: 528,
  174: 2981,
  175: 4213,
  176: 326,
  177: 1623,
  178: 983,
  179: 1191,
  180: 1952,
  181: 1450,
  182: 475,
  183: 1169,
  184: 1205,
  185: 1288,
  186: 2413,
  187: 2300,
  188: 1354,
  189: 519,
  190: 1659,
  191: 524,
  192: 4083,
  193: 2300,
  194: 1454,
  195: 721,
  196: 719,
  197: 861,
  198: 2772,
  199: 826,
  200: 1177,
  201: 1282,
  202: 504,
  203: 1587,
  204: 757,
  205: 2073,
  206: 1146,
  207: 912,
  208: 1637,
  209: 2404,
  210: 373,
  211: 522,
  212: 517,
  213: 1846,
  214: 1204,
  215: 3767,
  216: 589,
  217: 5687,
  218: 379,
  219: 291,
  220: 1319,
  221: 764,
  222: 3203,
  223: 2297,
  224: 757,
  225: 201,
  226: 407,
  227: 789,
  228: 867,
  229: 191,
  230: 477,
  231: 662,
  232: 1984,
  233: 1039,
  234: 2610,
  235: 840,
  236: 831,
  237: 1608,
  238: 688,
  239: 281,
  240: 2319,
  241: 525,
  242: 2978,
  243: 315,
  244: 314189,
  245: nan,
  246: nan,
  247: nan,
  248: nan,
  249: nan,
  250: nan,
  251: nan,
  252: nan,
  253: nan},
 '06': {0: 'Radetiketter',
  1: '7 Juni Plassen',
  2: 'Adamstuen',
  3: 'AHO',
  4: 'Akersgata',
  5: 'Alexander Kiellands Plass',
  6: 'Anker Hostel',
  7: 'Annette Thommessens Plass',
  8: 'Arendalsgata',
  9: 'Arkaden Nord',
  10: 'Arkaden Sør',
  11: 'Arkitekt Rivertz Plass',
  12: 'Badebakken',
  13: 'Bak Niels Treschows hus nord',
  14: 'Bak Niels Treschows hus sør',
  15: 'Bankplassen',
  16: 'Bentsebrugata',
  17: 'Bernt Ankers gate',
  18: 'BI Nydalen',
  19: 'Birkelunden',
  20: "Biskop Gunnerus' gate",
  21: 'Bislett Stadion',
  22: 'Bislettgata',
  23: 'Bjerregaards gate',
  24: 'Bjerregaardsgate Øst',
  25: 'Bjølsen mølle',
  26: 'Bjølsen Studentby',
  27: 'Bjølsendumpa',
  28: 'Bjørvika',
  29: 'Blindern studentparkering',
  30: 'Bogstadveien',
  31: 'Botanisk Hage sør',
  32: 'Botanisk hage sør-vest',
  33: 'Botanisk Hage vest',
  34: 'Briskeby',
  35: 'Bryn T-Bane',
  36: 'Bygdøy allé',
  37: 'Bøkkerveien',
  38: 'Carl Berners plass sør',
  39: 'Chr. Michelsens Gate',
  40: 'Colbjørnsens gate',
  41: 'Colletts gate',
  42: 'Colosseum Kino',
  43: 'Det Teologiske fakultet',
  44: 'Diakonhjemmet',
  45: 'Dokkveien',
  46: 'Drammensveien',
  47: 'Dyvekes bru',
  48: 'Dælenenggata',
  49: 'Edvard Storms gate',
  50: 'Elisenberg',
  51: 'Enerhaugen',
  52: 'Ensjø T-Bane',
  53: 'Ensjøveien',
  54: 'Fagerheimgata',
  55: 'Filipstadveien',
  56: 'Finnmarksgata',
  57: 'Forskningsveien',
  58: 'Fram-gården',
  59: 'Fred Olsens gate',
  60: 'Fredensborg',
  61: 'Friggfeltet',
  62: 'Frogner plass',
  63: 'Frogner Stadion',
  64: 'Frogner Tennisklubb',
  65: 'Frognerbadet',
  66: 'Frognerstranda',
  67: 'Frognerveien',
  68: 'Frøen T-bane',
  69: 'Furulund',

In [11]:
one = df1[['04','05','06','07','08','09','10']].melt().rename({'variable':'','value':'COL1.'},axis=1)
one

                   COL1.
0     04    Radetiketter
1     04  7 Juni Plassen
2     04       Adamstuen
3     04             AHO
4     04       Akersgata
...   ..             ...
1773  10      Økernveien
1774  10        Totalsum
1775  10             NaN
1776  10             NaN
1777  10             NaN

[1778 rows x 2 columns]

In [12]:
two = df1[['c_april','c_may','c_jun','c_july','c_aug','c_sep','c_oct']].melt().drop('variable',axis=1).rename({'value':'count'},axis=1)
two

                   count
0     Antall av ended_at
1                   1293
2                    567
3                   1799
4                   2418
...                  ...
1773                 185
1774              193868
1775                 NaN
1776                 NaN
1777                 NaN

[1778 rows x 1 columns]

In [13]:
out = pd.concat([one,two],axis=1).reindex(['COL1.','count',''], axis=1)
out = out.replace(np.nan, '', regex=True)
out = out[1:]
out = out.rename(columns={'': 'month'})
out

                          COL1.   count month
1                7 Juni Plassen    1293    04
2                     Adamstuen     567    04
3                           AHO    1799    04
4                     Akersgata    2418    04
5     Alexander Kiellands Plass    3238    04
...                         ...     ...   ...
1773                 Økernveien     185    10
1774                   Totalsum  193868    10
1775                                       10
1776                                       10
1777                                       10

[1777 rows x 3 columns]

In [14]:
out['month'] = out['month'].astype('int64')
out

                          COL1.   count  month
1                7 Juni Plassen    1293      4
2                     Adamstuen     567      4
3                           AHO    1799      4
4                     Akersgata    2418      4
5     Alexander Kiellands Plass    3238      4
...                         ...     ...    ...
1773                 Økernveien     185     10
1774                   Totalsum  193868     10
1775                                        10
1776                                        10
1777                                        10

[1777 rows x 3 columns]

In [15]:
out.columns.tolist()

['COL1.', 'count', 'month']

In [16]:
dataTypeSeries = df3.dtypes
print('Data type of each column of Dataframe :')
print(dataTypeSeries)

Data type of each column of Dataframe :
Unnamed: 0                     int64
started_at                    object
ended_at                      object
duration                       int64
start_station_id               int64
start_station_name            object
start_station_description     object
start_station_latitude       float64
start_station_longitude      float64
end_station_id                 int64
end_station_name              object
end_station_description       object
end_station_latitude         float64
end_station_longitude        float64
dtype: object

In [17]:
#The shape of data set.
print('The shape of our features is:', df3.shape)
df3=df3.replace(np.nan,0)

The shape of our features is: (235713, 14)

In [18]:
df3.isnull().sum()

Unnamed: 0                   0
started_at                   0
ended_at                     0
duration                     0
start_station_id             0
start_station_name           0
start_station_description    0
start_station_latitude       0
start_station_longitude      0
end_station_id               0
end_station_name             0
end_station_description      0
end_station_latitude         0
end_station_longitude        0
dtype: int64

In [19]:
df5['start_station_id'].nunique()

247

In [20]:
res1 = df3.append(df4).reset_index()
res2 = res1.append(df5).reset_index()
res2=res2.drop(['level_0','index','Unnamed: 0'], axis=1)

res3 = res2.append(df6).reset_index()

res4 = res3.append(df7).reset_index()
res4=res4.drop(['level_0','index'], axis=1)


res5 = res4.append(df8).reset_index()

result = res5.append(df9).reset_index()
result=result.drop(['index','Unnamed: 0'], axis=1)

In [21]:
result['month'] = pd.DatetimeIndex(result['started_at']).month
result[:3]

,level_0,started_at,ended_at,duration,start_station_id,start_station_name,start_station_description,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_description,end_station_latitude,end_station_longitude,month
0,0,2019-04-02 22:18:47.926000+00:00,2019-04-02 22:24:25.427000+00:00,337,401,Schous plass,nærmest Thorvald Meyers gate,59.920259,10.760629,381,Grønlands torg,ved Tøyenbekken,59.912520,10.762240,4
1,1,2019-04-02 22:25:54.203000+00:00,2019-04-02 22:27:36.114000+00:00,101,556,Pilestredet,ved Sporveisgata,59.926224,10.729625,556,Pilestredet,ved Sporveisgata,59.926224,10.729625,4
2,2,2019-04-02 22:26:39.308000+00:00,2019-04-02 22:31:59.445000+00:00,320,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,4

In [22]:
print(result['month'].unique())

[ 4  5  6  7  8  9 10]

In [23]:
result['start_station_name'].nunique()

259

In [24]:
result['combined'] = result['start_station_id'].astype(str)+result['end_station_id'].astype(str)
result[:3]

,level_0,started_at,ended_at,duration,start_station_id,start_station_name,start_station_description,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_description,end_station_latitude,end_station_longitude,month,combined
0,0,2019-04-02 22:18:47.926000+00:00,2019-04-02 22:24:25.427000+00:00,337,401,Schous plass,nærmest Thorvald Meyers gate,59.920259,10.760629,381,Grønlands torg,ved Tøyenbekken,59.912520,10.762240,4,401381
1,1,2019-04-02 22:25:54.203000+00:00,2019-04-02 22:27:36.114000+00:00,101,556,Pilestredet,ved Sporveisgata,59.926224,10.729625,556,Pilestredet,ved Sporveisgata,59.926224,10.729625,4,556556
2,2,2019-04-02 22:26:39.308000+00:00,2019-04-02 22:31:59.445000+00:00,320,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,4,561471

In [30]:
result['combined'].nunique()
#we just have 54777 uniqe FROM to TO station . #lets sum the duration of each similar row.
#and drop the duplicate row.

57544

In [31]:
#Group by based on the combined id and we some the duration 
result["sum"] = result.groupby('combined')['duration'].transform('sum')
df1 = result.drop_duplicates('combined')
df1[:10]

,level_0,started_at,ended_at,duration,start_station_id,start_station_name,start_station_description,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_description,end_station_latitude,end_station_longitude,month,combined,sum
0,0,2019-04-02 22:18:47.926000+00:00,2019-04-02 22:24:25.427000+00:00,337,401,Schous plass,nærmest Thorvald Meyers gate,59.920259,10.760629,381,Grønlands torg,ved Tøyenbekken,59.912520,10.762240,4,401381,32290
1,1,2019-04-02 22:25:54.203000+00:00,2019-04-02 22:27:36.114000+00:00,101,556,Pilestredet,ved Sporveisgata,59.926224,10.729625,556,Pilestredet,ved Sporveisgata,59.926224,10.729625,4,556556,35628
2,2,2019-04-02 22:26:39.308000+00:00,2019-04-02 22:31:59.445000+00:00,320,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,4,561471,12867
3,3,2019-04-03 03:09:58.992000+00:00,2019-04-03 03:12:00.589000+00:00,121,393,Hans Nielsen Hauges plass,Mellom Åsengata og Nordkappgata,59.939244,10.774319,393,Hans Nielsen Hauges plass,Mellom Åsengata og Nordkappgata,59.939244,10.774319,4,393393,195132
4,4,2019-04-03 03:10:02.415000+00:00,2019-04-03 03:14:44.537000+00:00,282,597,Fredensborg,ved rundkjøringen,59.920995,10.750358,557,Akersgata,ved Grensen,59.914197,10.742883,4,597557,190271
5,5,2019-04-03 03:16:21.557000+00:00,2019-04-03 03:27:20.124000+00:00,658,471,Marienlyst,i Suhms gate,59.932454,10.721769,412,Jakob kirke,langs Torggata,59.917866,10.754898,4,471412,12700
6,6,2019-04-03 03:39:11.948000+00:00,2019-04-03 03:42:46.377000+00:00,214,598,Sofienbergparken nord,langs Helgesens gate,59.923229,10.766171,401,Schous plass,nærmest Thorvald Meyers gate,59.920259,10.760629,4,598401,44248
7,7,2019-04-03 03:43:38.513000+00:00,2019-04-03 03:50:02.914000+00:00,384,462,Stensparken,ved Sporveisgata,59.927140,10.730981,613,Schives gate,ved Arno Bergs plass,59.920804,10.714054,4,462613,19203
8,8,2019-04-03 03:46:23.126000+00:00,2019-04-03 04:00:40.509000+00:00,857,461,Vålerenga,langs Ingeborgs gate,59.908576,10.786856,385,Søndre gate,ved Ankerbrua,59.918632,10.757867,4,461385,21880
9,9,2019-04-03 03:50:36.147000+00:00,2019-04-03 03:56:15.344000+00:00,339,463,Schous plass trikkestopp,ved biblioteket,59.920728,10.759486,448,Oslo Plaza,ved rundkjøringen,59.912185,10.754506,4,463448,31665

In [32]:
check = result[result['combined'].str.contains('561471')]
check

,level_0,started_at,ended_at,duration,start_station_id,start_station_name,start_station_description,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_description,end_station_latitude,end_station_longitude,month,combined,sum
2,2,2019-04-02 22:26:39.308000+00:00,2019-04-02 22:31:59.445000+00:00,320,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,4,561471,12867
24335,24335,2019-04-06 14:34:38.038000+00:00,2019-04-06 14:37:01.427000+00:00,143,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,4,561471,12867
53253,53253,2019-04-10 13:43:58.701000+00:00,2019-04-10 13:52:50.666000+00:00,531,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,4,561471,12867
147901,147901,2019-04-22 19:55:19.710000+00:00,2019-04-22 19:56:55.466000+00:00,95,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,4,561471,12867
308640,308640,2019-05-07 22:48:59.242000+00:00,2019-05-07 23:42:01.050000+00:00,3181,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,5,561471,12867
433282,433282,2019-05-20 20:16:03.985000+00:00,2019-05-20 20:18:19.009000+00:00,135,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,5,561471,12867
549657,549657,2019-05-30 21:25:26.538000+00:00,2019-05-30 21:38:05.733000+00:00,759,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,5,561471,12867
635364,635364,2019-06-09 14:15:50.617000+00:00,2019-06-09 15:24:53.620000+00:00,4143,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,6,561471,12867
687483,687483,2019-06-14 11:56:09.731000+00:00,2019-06-14 11:57:39.176000+00:00,89,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,6,561471,12867
861618,861618,2019-06-28 17:39:58.105000+00:00,2019-06-28 17:41:50.797000+00:00,112,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,6,561471,12867
899565,899565,2019-07-02 21:34:40.358000+00:00,2019-07-02 21:36:05.844000+00:00,85,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,7,561471,12867
1070540,1070540,2019-07-18 21:40:58.960000+00:00,2019-07-18 21:58:21.247000+00:00,1042,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,7,561471,12867
1086532,1086532,2019-07-21 13:38:53.867000+00:00,2019-07-21 13:40:29.617000+00:00,95,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,7,561471,12867
1110515,1110515,2019-07-23 22:02:08.356000+00:00,2019-07-23 22:04:30.181000+00:00,141,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,7,561471,12867
1173421,1173421,2019-07-29 17:13:09.242000+00:00,2019-07-29 17:31:19.959000+00:00,1090,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,7,561471,12867
1296274,1296274,2019-08-09 13:22:01.463000+00:00,2019-08-09 13:24:12.990000+00:00,131,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,8,561471,12867
1466939,1466939,2019-08-23 10:56:05.969000+00:00,2019-08-23 10:57:47.137000+00:00,101,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,8,561471,12867
1513177,1513177,2019-08-26 20:03:38.340000+00:00,2019-08-26 20:05:30.361000+00:00,112,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,8,561471,12867
1864356,1864356,2019-09-29 14:44:56.073000+00:00,2019-09-29 14:46:52.428000+00:00,116,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,9,561471,12867
1875025,8017,2019-10-01 16:14:12.596000+00:00,2019-10-01 16:15:53.166000+00:00,100,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,10,561471,12867
1886157,19149,2019-10-02 20:17:57.838000+00:00,2019-10-02 20:19:32.849000+00:00,95,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,10,561471,12867
1929980,62972,2019-10-09 13:47:44.409000+00:00,2019-10-09 13:50:04.302000+00:00,139,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,10,561471,12867
1952220,85212,2019-10-12 13:46:47.558000+00:00,2019-10-12 13:48:39.705000+00:00,112,561,Kirkeveien,nord for Gørbitz' gate,59.933558,10.726426,471,Marienlyst,i Suhms gate,59.932454,10.721769,10,561471,12867

In [28]:
out= out.rename({'COL1.': 'start_station_name'}, axis=1)
out[:3]

  start_station_name count  month
1     7 Juni Plassen  1293      4
2          Adamstuen   567      4
3                AHO  1799      4

In [36]:
check2 = out[out['start_station_name']=='Schous plass']
check2

     start_station_name count  month
168        Schous plass  2633      4
421        Schous plass  3516      5
680        Schous plass  3601      6
935        Schous plass  3181      7
1191       Schous plass  4233      8
1443       Schous plass  3200      9
1697       Schous plass  2284     10

In [53]:
df1.shape

(57544, 17)

In [35]:
result2=df1.merge(out,right_on=['start_station_name','month'],left_on=['start_station_name','month'])
result2

,level_0,started_at,ended_at,duration,start_station_id,start_station_name,start_station_description,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_description,end_station_latitude,end_station_longitude,month,combined,sum,count
0,0,2019-04-02 22:18:47.926000+00:00,2019-04-02 22:24:25.427000+00:00,337,401,Schous plass,nærmest Thorvald Meyers gate,59.920259,10.760629,381,Grønlands torg,ved Tøyenbekken,59.912520,10.762240,4,401381,32290,2633
1,49,2019-04-03 04:39:16.854000+00:00,2019-04-03 04:44:40.769000+00:00,323,401,Schous plass,nærmest Thorvald Meyers gate,59.920259,10.760629,478,Jernbanetorget,på Europarådets plass,59.911901,10.749929,4,401478,45174,2633
2,94,2019-04-03 04:53:45.393000+00:00,2019-04-03 05:02:00.970000+00:00,495,423,Schous plass,nærmest rundkjøringen,59.920335,10.760804,422,St. Hanshaugen,i Waldemar Thranes gate,59.923703,10.740542,4,423422,26826,2633
3,167,2019-04-03 05:11:58.798000+00:00,2019-04-03 05:20:12.573000+00:00,493,423,Schous plass,nærmest rundkjøringen,59.920335,10.760804,573,Tordenskiolds gate,Mellom Rådhusplassen og Otto Sverdrups gate,59.911788,10.735165,4,423573,20496,2633
4,320,2019-04-03 05:35:24.346000+00:00,2019-04-03 05:43:52.107000+00:00,507,423,Schous plass,nærmest rundkjøringen,59.920335,10.760804,396,Kirkeristen,ved Torggata,59.913032,10.746681,4,423396,142627,2633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57505,180679,2019-10-29 07:01:34.982000+00:00,2019-10-29 07:21:48.950000+00:00,1213,593,Bjølsen mølle,i Sandakerveien utenfor siloen,59.939200,10.768774,567,Forskningsveien,ved Nordre Aker,59.945478,10.713847,10,593567,1213,272
57506,181606,2019-10-29 08:02:30.283000+00:00,2019-10-29 08:15:03.229000+00:00,752,738,Lodalen busstopp,langs Dyvekes vei,59.903453,10.777958,1101,Stortingstunellen,ved Rådhusgata,59.910653,10.737365,10,7381101,752,204
57507,184932,2019-10-29 16:18:04.566000+00:00,2019-10-29 16:29:17.845000+00:00,673,382,Stensgata,ved trikkestoppet,59.929634,10.732839,1101,Stortingstunellen,ved Rådhusgata,59.910653,10.737365,10,3821101,673,597
57508,189487,2019-10-30 10:42:21.424000+00:00,2019-10-30 11:01:39.120000+00:00,1157,452,Vippetangen vest,nærmest Rådhuset,59.903989,10.740627,470,St. Hanshaugen park nord,krysset Colletts gt / Geitmyrsveien,59.929771,10.743524,10,452470,1157,1092
57509,191448,2019-10-30 15:38:49.444000+00:00,2019-10-30 15:42:43.772000+00:00,234,545,Arkaden Sør,ved Dronningens gate,59.911969,10.747858,1101,Stortingstunellen,ved Rådhusgata,59.910653,10.737365,10,5451101,234,505

In [37]:
result2['mul'] = result2['sum'].mul(result2['count'])

In [38]:
result_sort = result2.sort_values(['mul'], ascending=[False])
result_sort[:10]

,level_0,started_at,ended_at,duration,start_station_id,start_station_name,start_station_description,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_description,end_station_latitude,end_station_longitude,month,combined,sum,count,mul
4397,3987,2019-04-03 17:28:58.241000+00:00,2019-04-03 17:53:50.938000+00:00,1492,494,Rådhusbrygge 4,ved Nesoddbåten,59.910847,10.730377,494,Rådhusbrygge 4,ved Nesoddbåten,59.910847,10.730377,4,494494,1546825,6101,9437179325
4363,95,2019-04-03 04:54:01.563000+00:00,2019-04-03 05:01:11.925000+00:00,430,494,Rådhusbrygge 4,ved Nesoddbåten,59.910847,10.730377,443,Sjøsiden øst,nærmest trappen,59.910178,10.751824,4,494443,843761,6101,5147785861
4440,12475,2019-04-04 19:31:03.056000+00:00,2019-04-04 19:43:06.259000+00:00,723,494,Rådhusbrygge 4,ved Nesoddbåten,59.910847,10.730377,392,Sjøsiden vest,nærmest fontenen,59.910178,10.751224,4,494392,715447,6101,4364942147
4475,25251,2019-04-06 15:58:50.512000+00:00,2019-04-06 16:20:25.934000+00:00,1295,494,Rådhusbrygge 4,ved Nesoddbåten,59.910847,10.730377,599,Paléhaven,langs Strandgata,59.910331,10.750110,4,494599,691644,6101,4219720044
22231,544,2019-04-03 05:58:06.168000+00:00,2019-04-03 06:12:17.086000+00:00,850,479,Tjuvholmen,nedenfor bussholdeplassen,59.909467,10.722509,479,Tjuvholmen,nedenfor bussholdeplassen,59.909467,10.722509,4,479479,1208989,3301,3990872689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57058,182562,2019-10-29 11:52:51.361000+00:00,2019-10-29 11:55:17.746000+00:00,146,1101,Stortingstunellen,ved Rådhusgata,59.910653,10.737365,787,Kirkegata 15,Kirkegata 15,59.910156,10.743457,10,1101787,146,233,34018
54032,1292071,2019-08-09 07:35:55.738000+00:00,2019-08-09 07:45:21.955000+00:00,566,560,Gaustad T-bane,ved Slemdalsveien,59.945955,10.710392,626,Drammensveien,ved Ingar Nilsens vei,59.920404,10.691147,8,560626,566,59,33394
57148,72618,2019-10-10 15:21:03.957000+00:00,2019-10-10 15:35:17.337000+00:00,853,601,Rolf Wickstrøms vei,ved Bergrådveien,59.953411,10.757724,605,Økernveien,ved Ensjøveien bussholdeplass,59.916738,10.779916,10,601605,853,36,30708
45633,459932,2019-05-22 19:29:16.199000+00:00,2019-05-22 19:39:58.363000+00:00,642,601,Rolf Wickstrøms vei,ved Bergrådveien,59.953411,10.757724,451,Suhms gate,mellom Schultz' gate og Industrigata,59.929419,10.726195,5,601451,642,39,25038
12348,145225,2019-04-22 16:26:57.166000+00:00,2019-04-22 16:32:34.894000+00:00,337,498,HasleLinje,ved Anders Winsvolds vei,59.927641,10.799201,415,Sinsenveien,ved Kongehellegata,59.929542,10.781053,4,498415,337,67,22579

In [59]:
print(out.shape)
print(result.shape)
print(df1.shape)

(2031, 3)
(2060876, 17)
(57544, 17)